local _2afile_2a = "fnl/katdotnvim/utils/export/init.fnl"
local _2amodule_name_2a = "katdotnvim.utils.export.init"
local _2amodule_2a
do
  package.loaded[_2amodule_name_2a] = {}
  _2amodule_2a = package.loaded[_2amodule_name_2a]
end
local _2amodule_locals_2a
do
  _2amodule_2a["aniseed/locals"] = {}
  _2amodule_locals_2a = (_2amodule_2a)["aniseed/locals"]
end
local autoload = (require("katdotnvim.aniseed.autoload")).autoload
local a, colors, groups, hsl, kitty, main, ucolors, _ = autoload("katdotnvim.aniseed.core"), autoload("katdotnvim.color"), autoload("katdotnvim.highlights.main"), autoload("externals.hsluv"), autoload("katdotnvim.utils.export.kitty"), autoload("katdotnvim.main"), autoload("katdotnvim.utils.color"), nil
_2amodule_locals_2a["a"] = a
_2amodule_locals_2a["colors"] = colors
_2amodule_locals_2a["groups"] = groups
_2amodule_locals_2a["hsl"] = hsl
_2amodule_locals_2a["kitty"] = kitty
_2amodule_locals_2a["main"] = main
_2amodule_locals_2a["ucolors"] = ucolors
_2amodule_locals_2a["_"] = _
local function generateString(colors0, terminal)
  local output = string.format("# %s terminal theme generated by kat.nvim\n# Generated using %s colorscheme with background set to %s\n\n", terminal, tostring(vim.g.colors_name), tostring(vim.o.background))
  for key, val in pairs(colors0) do
    output = string.format("%s%s %s\n", output, key, val)
  end
  return output
end
_2amodule_2a["generateString"] = generateString
local function userExportNotify(terminal)
  return vim.notify(string.format("kat.nvim: %s color file generated at cwd using %s colorscheme with %s background", terminal, tostring(vim.g.colors_name), tostring(vim.o.background)), vim.log.levels.INFO)
end
_2amodule_2a["userExportNotify"] = userExportNotify
local function generateTerminalColors(terminal)
  local _1_ = tostring(terminal)
  if (_1_ == "kitty") then
    return kitty.generateKittyTheme()
  else
    return nil
  end
end
_2amodule_2a["generateTerminalColors"] = generateTerminalColors
do
  vim.api.nvim_command("command! -nargs=1 KatGenTermTheme lua require('katdotnvim.utils.export.init').generateTerminalColors(<args>)")
end
return _2amodule_2a